# Dockerfile.dev (개발 환경)

# 개발 환경에서 사용할 도커 이미지를 지정합니다.
FROM node:14

# 앱 소스코드를 복사할 디렉토리를 지정합니다.
WORKDIR '/app'

# package.json 및 package-lock.json을 복사하여 종속성을 먼저 설치합니다.
COPY package.json .
COPY package-lock.json .
RUN npm install

# 소스 코드를 현재 디렉토리로 복사합니다.
COPY . .

# Python을 설치합니다.
RUN apt-get update || : && apt-get install python -y python-pip

# Python 패키지를 설치합니다.
RUN pip install xgboost 
RUN pip install numpy 
RUN pip install pandas 
RUN pip install scikit-learn

# 개발 서버를 시작합니다.
CMD ["npm", "run", "start"]


